module.exports = {
    "Kharkion": {
        name: "Kharkion",
        description: "Doesn’t damage the environment in the extraction process, finite amount",
        price: 150,
        amount: 80,
        available: 80,
        cost: 150,
        points: 5,
    },
	"Trezorkite": {
		name: "Trezorkite",
		description: "Causes irreversible environmental damage in extraction process, finite amount",
		price: 150,
		amount: 80,
		available: 80,
		cost: 150,
		points: 3,
	},
	"Solar Farms": {
		name: "Solar Farms",
		description: "Very limited environmental impact, infinite amount",
		price: 300,
		amount: 80,
		available: 80,
		cost: 300,
		points: 9,
	},
	"Nuclear Power": {
		name: "Nuclear Power",
		description: "Very limited environmental impact, infinite amount, very unlikely but high risk",
		price: 375,
		amount: 80,
		available: 80,
		cost: 375,
		points: 12,
	},
};