module.exports = {
    "Pludupudupe": {
        name: "Pludupudupe",
        description: "Low cost, medium durability. Unpleasant aesthetics. Useful for low to mid-level infrastructure projects",
        price: 32.5,
        amount: 80,
        available: 80,
        cost: 32.5,
        points: 1,
    },
	"Posteelium": {
		name: "Posteelium",
		description: "Medium Cost, Medium Durability. Pleasant aesthetics.  Useful for mid to low high level infrastructure projects",
		price: 45,
		amount: 80,
		available: 80,
		cost: 45,
		points: 1.5,
	},
	"Reclium": {
		name: "Reclium",
		description: "High cost, High durability, Pleasant Aesthetics, Useful for high level infrastructure projects",
		price: 62.5,
		amount: 80,
		available: 80,
		cost: 62.5,
		points: 2,
	},
	"Plenomium": {
		name: "Plenomium",
		description: "Extremely high cost, Virtually Inds0tructible, Useful for extremely high level infrastructure products and military goods",
		price: 115,
		amount: 80,
		available: 80,
		cost: 115,
		points: 3.5,
	},
};